"""Create user achievement association table

Revision ID: cabe4f0b55ec
Revises: d58e6f0bbc36
Create Date: 2024-04-04 10:32:49.535714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cabe4f0b55ec"
down_revision: Union[str, None] = "d58e6f0bbc36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_achievement_associations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "achievement_id", name="unique_user_achievement"),
    )
    op.create_index(
        op.f("ix_user_achievement_associations_id"),
        "user_achievement_associations",
        ["id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_achievement_associations_id"),
        table_name="user_achievement_associations",
    )
    op.drop_table("user_achievement_associations")
    # ### end Alembic commands ###
